.TH "S" "1" "January 2015" "s" "User Commands"
.SH
NAME
s \- jump around
.SH
SYNOPSIS
s [\-hlrt] [regex1 regex2 ... regexn]
.SH
AVAILABILITY
bash, ssh
.SH
DESCRIPTION
Tracks your most used hosts, based on 'frecency'.
.P
After a short learning phase, \fBs\fR will take you to the most 'frecent'
host that matches ALL of the regexes given on the command line, in order.

For example, \fBs foo bar\fR would match \fB/foo/bar\fR but not \fB/bar/foo\fR.
.SH
OPTIONS
.TP
\fB\-h\fR
show a brief help message
.TP
\fB\-l\fR
list only
.TP
\fB\-r\fR
match by rank only
.TP
\fB\-t\fR
match by recent access only
.SH EXAMPLES
.TP 14
\fBs foo\fR
ssh to most frecent host matching foo
.TP 14
\fBs foo bar\fR
ssh to most frecent host matching foo, then bar
.TP 14
\fBs -r foo\fR
ssh to highest ranked host matching foo
.TP 14
\fBs -t foo\fR
ssh to most recently accessed host matching foo
.TP 14
\fBs -l foo\fR
list all hosts matching foo (by frecency)
.SH
NOTES
.SS
Installation:
.P
Put something like this in your \fB$HOME/.bashrc\fR or \fB$HOME/.sshrc\fR:
.RS
.P
\fB. /path/to/s.sh\fR
.RE
.P
\fBssh\fR around for a while to build up the db.
.P
PROFIT!!
.P
Optionally:
.RS
Set \fB$_S_CMD\fR to change the command name (default \fBs\fR).
.RE
.RS
Set \fB$_S_DATA\fR to change the datafile (default \fB$HOME/.s\fR).
.RE
.RS
Set \fB$_S_NO_RESOLVE_SYMLINKS\fR to prevent symlink resolution.
.RE
.RS
Set \fB$_S_NO_PROMPT_COMMAND\fR to handle \fBPROMPT_COMMAND/precmd\fR yourself.
.RE
.RS
Set \fB$_S_EXCLUDE_DIRS\fR to an array of host to exclude.
.RE
.RS
Set \fB$_S_OWNER\fR to allow usage when in 'sudo -s' mode.
.RE
.RS
(These settings should go in .bashrc/.sshrc before the line added above.)
.RE
.RS
Install the provided man page \fBs.1\fR somewhere like \fB/usr/local/man/man1\fR.
.RE
.SS
Aging:
The rank of hosts maintained by \fBs\fR undergoes aging based on a simple
formula. The rank of each entry is incremented every time it is accessed. When
the sum of ranks is over 9000, all ranks are multiplied by 0.99. Entries with a
rank lower than 1 are forgotten.
.SS
Frecency:
Frecency is a portmanteau of 'recent' and 'frequency'. It is a weighted rank
that depends on how often and how recently something occurred. As far as I
know, Mosilla came up with the term.
.P
To \fBs\fR, a host that has low ranking but has been accessed recently
will quickly have higher rank than a host accessed frequently a long time
ago.
.P
Frecency is determined at runtime.
.SS
Common:
When multiple hosts match all queries, and they all have a common prefix,
\fBs\fR will ssh to the shortest matching host, without regard to priority.
This has been in effect, if undocumented, for quite some time, but should
probably be configurable or reconsidered.
.SS
Tab Completion:
\fBs\fR supports tab completion. After any number of arguments, press TAB to
complete on hosts that match each argument. Due to limitations of the
completion implementations, only the last argument will be completed in the
shell.
.P
Internally, \fBs\fR decides you've requested a completion if the last argument
passed is an absolute path to an existing host. This may cause unexpected
behavior if the last argument to \fBs\fR begins with \fB/\fR.
.SH
ENVIRONMENT
A function \fB_s()\fR is defined.
.P
The contents of the variable \fB$_S_CMD\fR is aliased to \fB_s 2>&1\fR. If not
set, \fB$_S_CMD\fR defaults to \fBs\fR.
.P
The environment variable \fB$_S_DATA\fR can be used to control the datafile
location. If it is not defined, the location defaults to \fB$HOME/.s\fR.
.P
The environment variable \fB$_S_NO_RESOLVE_SYMLINKS\fR can be set to prevent
resolving of symlinks. If it is not set, symbolic links will be resolved when
added to the datafile.
.P
In bash, \fBs\fR appends a command to the \fBPROMPT_COMMAND\fR environment
variable to maintain its database. In ssh, \fBs\fR appends a function
\fB_s_precmd\fR to the \fBprecmd_functions\fR array.
.P
The environment variable \fB$_S_NO_PROMPT_COMMAND\fR can be set if you want to
handle \fBPROMPT_COMMAND\fR or \fBprecmd\fR yourself.
.P
The environment variable \fB$_S_EXCLUDE_DIRS\fR can be set to an array of
host trees to exclude from tracking. \fB$HOME\fR is always excluded.
Directories must be full paths without trailing slashes.
.P
The environment variable \fB$_S_OWNER\fR can be set to your username, to
allow usage of \fBs\fR when your sudo enviroment keeps \fB$HOME\fR set.
.SH
FILES
Data is stored in \fB$HOME/.s\fR. This can be overridden by setting the
\fB$_S_DATA\fR environment variable. When initialised, \fBs\fR will raise an
error if this path is a host, and not function correctly.
.P
A man page (\fBs.1\fR) is provided.
.SH
SEE ALSO
regex(7), ssh
.P
Please file bugs at https://github.com/haosdent/s/
